workspace(name = "greetings", managed_directories = {"@npm": ["node_modules"]})

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_dotnet",
    remote = "https://github.com/bazelbuild/rules_dotnet",
    commit = "e6415707f7e26756456d2473b9b22dfbeff66171",
)

http_archive(
    name = "build_bazel_rules_svelte",
    url = "https://github.com/thelgevold/rules_svelte/archive/0.15.zip",
    strip_prefix = "rules_svelte-0.15",
    sha256 = "1b04eb08ef80636929d152bb2f2733e36d9e0b8ad10aca7b435c82bd638336f5"
) 

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "591d2945b09ecc89fde53e56dd54cfac93322df3bc9d4747cb897ce67ba8cdbf",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.2.0/rules_nodejs-1.2.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "core_register_sdk",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
    "nuget_package"
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

core_register_sdk(
    "v3.1.100",
)

core_register_sdk(
    "v3.1.100",
    name = "core_sdk",
)

load("@build_bazel_rules_svelte//:defs.bzl", "rules_svelte_dependencies")
rules_svelte_dependencies()

### Generated by the tool
nuget_package(
    name = "messagepack.annotations",
    package = "messagepack.annotations",
    version = "2.1.152",
    sha256 = "838daf42e724a174cb232c4f4430855501e4418f356ce72334829eafbae3daa4",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "netcoreapp2.1": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "netcoreapp3.0": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "netcoreapp3.1": "lib/netstandard2.0/MessagePack.Annotations.dll",
    },
    net_lib = {
        "net461": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "net462": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "net47": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "net471": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "net472": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "net48": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "netstandard2.0": "lib/netstandard2.0/MessagePack.Annotations.dll",
        "netstandard2.1": "lib/netstandard2.0/MessagePack.Annotations.dll",
    },
    mono_lib = "lib/netstandard2.0/MessagePack.Annotations.dll",
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
    },
    net_files = {
        "net461": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "net462": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "net47": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "net471": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "net472": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "net48": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/MessagePack.Annotations.dll",
           "lib/netstandard2.0/MessagePack.Annotations.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/MessagePack.Annotations.dll",
        "lib/netstandard2.0/MessagePack.Annotations.xml",
    ],
)
nuget_package(
    name = "system.buffers",
    package = "system.buffers",
    version = "4.5.1",
    sha256 = "c30b3dd2c7e2f4cee4b823d692fd42118309b42ab1f5007f923d329a5b0d6b12",
    net_lib = {
        "net45": "lib/netstandard1.1/System.Buffers.dll",
        "net451": "lib/netstandard1.1/System.Buffers.dll",
        "net452": "lib/netstandard1.1/System.Buffers.dll",
        "net46": "lib/netstandard1.1/System.Buffers.dll",
        "net461": "lib/net461/System.Buffers.dll",
        "net462": "lib/net461/System.Buffers.dll",
        "net47": "lib/net461/System.Buffers.dll",
        "net471": "lib/net461/System.Buffers.dll",
        "net472": "lib/net461/System.Buffers.dll",
        "net48": "lib/net461/System.Buffers.dll",
        "netstandard1.1": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard1.2": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard1.3": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard1.4": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard1.5": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard1.6": "lib/netstandard1.1/System.Buffers.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Buffers.dll",
        "netstandard2.1": "lib/netstandard2.0/System.Buffers.dll",
    },
    net_ref = {
        "net45": "ref/net45/System.Buffers.dll",
        "net451": "ref/net45/System.Buffers.dll",
        "net452": "ref/net45/System.Buffers.dll",
        "net46": "ref/net45/System.Buffers.dll",
        "net461": "ref/net45/System.Buffers.dll",
        "net462": "ref/net45/System.Buffers.dll",
        "net47": "ref/net45/System.Buffers.dll",
        "net471": "ref/net45/System.Buffers.dll",
        "net472": "ref/net45/System.Buffers.dll",
        "net48": "ref/net45/System.Buffers.dll",
        "netstandard1.1": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard1.2": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard1.3": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard1.4": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard1.5": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard1.6": "ref/netstandard1.1/System.Buffers.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Buffers.dll",
        "netstandard2.1": "ref/netstandard2.0/System.Buffers.dll",
    },
    mono_lib = "lib/net461/System.Buffers.dll",
    mono_ref = "ref/net45/System.Buffers.dll",
    net_files = {
        "net45": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "net451": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "net452": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "net46": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "net461": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "net462": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "net47": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "net471": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "net472": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "net48": [
           "lib/net461/System.Buffers.dll",
           "lib/net461/System.Buffers.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.1/System.Buffers.dll",
           "lib/netstandard1.1/System.Buffers.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Buffers.dll",
           "lib/netstandard2.0/System.Buffers.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/System.Buffers.dll",
           "lib/netstandard2.0/System.Buffers.xml",
        ],
    },
    mono_files = [
        "lib/net461/System.Buffers.dll",
        "lib/net461/System.Buffers.xml",
    ],
)
nuget_package(
    name = "system.numerics.vectors",
    package = "system.numerics.vectors",
    version = "4.5.0",
    sha256 = "a9d49320581fda1b4f4be6212c68c01a22cdf228026099c20a8eabefcf90f9cf",
    net_lib = {
        "net45": "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
        "net451": "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
        "net452": "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
        "net46": "lib/net46/System.Numerics.Vectors.dll",
        "net461": "lib/net46/System.Numerics.Vectors.dll",
        "net462": "lib/net46/System.Numerics.Vectors.dll",
        "net47": "lib/net46/System.Numerics.Vectors.dll",
        "net471": "lib/net46/System.Numerics.Vectors.dll",
        "net472": "lib/net46/System.Numerics.Vectors.dll",
        "net48": "lib/net46/System.Numerics.Vectors.dll",
        "netstandard1.0": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.1": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.2": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.3": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.4": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.5": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.6": "lib/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Numerics.Vectors.dll",
        "netstandard2.1": "lib/netstandard2.0/System.Numerics.Vectors.dll",
    },
    net_ref = {
        "net45": "ref/net45/System.Numerics.Vectors.dll",
        "net451": "ref/net45/System.Numerics.Vectors.dll",
        "net452": "ref/net45/System.Numerics.Vectors.dll",
        "net46": "ref/net46/System.Numerics.Vectors.dll",
        "net461": "ref/net46/System.Numerics.Vectors.dll",
        "net462": "ref/net46/System.Numerics.Vectors.dll",
        "net47": "ref/net46/System.Numerics.Vectors.dll",
        "net471": "ref/net46/System.Numerics.Vectors.dll",
        "net472": "ref/net46/System.Numerics.Vectors.dll",
        "net48": "ref/net46/System.Numerics.Vectors.dll",
        "netstandard1.0": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.1": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.2": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.3": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.4": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.5": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard1.6": "ref/netstandard1.0/System.Numerics.Vectors.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Numerics.Vectors.dll",
        "netstandard2.1": "ref/netstandard2.0/System.Numerics.Vectors.dll",
    },
    mono_lib = "lib/net46/System.Numerics.Vectors.dll",
    mono_ref = "ref/net46/System.Numerics.Vectors.dll",
    net_files = {
        "net45": [
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.xml",
        ],
        "net451": [
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.xml",
        ],
        "net452": [
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.xml",
        ],
        "net46": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net461": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net462": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net47": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net471": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net472": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "net48": [
           "lib/net46/System.Numerics.Vectors.dll",
           "lib/net46/System.Numerics.Vectors.xml",
        ],
        "netstandard1.0": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.0/System.Numerics.Vectors.dll",
           "lib/netstandard1.0/System.Numerics.Vectors.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Numerics.Vectors.dll",
           "lib/netstandard2.0/System.Numerics.Vectors.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/System.Numerics.Vectors.dll",
           "lib/netstandard2.0/System.Numerics.Vectors.xml",
        ],
    },
    mono_files = [
        "lib/net46/System.Numerics.Vectors.dll",
        "lib/net46/System.Numerics.Vectors.xml",
    ],
)
nuget_package(
    name = "system.reflection.emit",
    package = "system.reflection.emit",
    version = "4.7.0",
    sha256 = "170fc24910fec1a8c7d4ca9f292dd0fec22b507ec63782be17e0f1ebc50f3488",
    net_lib = {
        "netstandard1.1": "lib/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.2": "lib/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.3": "lib/netstandard1.3/System.Reflection.Emit.dll",
        "netstandard1.4": "lib/netstandard1.3/System.Reflection.Emit.dll",
        "netstandard1.5": "lib/netstandard1.3/System.Reflection.Emit.dll",
        "netstandard1.6": "lib/netstandard1.3/System.Reflection.Emit.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Reflection.Emit.dll",
    },
    net_ref = {
        "netstandard1.1": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.2": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.3": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.4": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.5": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard1.6": "ref/netstandard1.1/System.Reflection.Emit.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Reflection.Emit.dll",
    },
    net_files = {
        "netstandard1.1": [
           "lib/netstandard1.1/System.Reflection.Emit.dll",
           "lib/netstandard1.1/System.Reflection.Emit.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.1/System.Reflection.Emit.dll",
           "lib/netstandard1.1/System.Reflection.Emit.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.3/System.Reflection.Emit.dll",
        ],
        "netstandard1.4": [
           "lib/netstandard1.3/System.Reflection.Emit.dll",
        ],
        "netstandard1.5": [
           "lib/netstandard1.3/System.Reflection.Emit.dll",
        ],
        "netstandard1.6": [
           "lib/netstandard1.3/System.Reflection.Emit.dll",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Reflection.Emit.dll",
           "lib/netstandard2.0/System.Reflection.Emit.xml",
        ],
    },
)
nuget_package(
    name = "system.reflection.emit.lightweight",
    package = "system.reflection.emit.lightweight",
    version = "4.7.0",
    sha256 = "5745b3fd45283481dd4c64bd7b54d1f3dbb9f33263a3fc0f516c3a55a5727255",
    net_lib = {
        "netstandard1.0": "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.1": "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.2": "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.3": "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.4": "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.5": "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.6": "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Reflection.Emit.Lightweight.dll",
    },
    net_ref = {
        "netstandard1.0": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.1": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.2": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.3": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.4": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.5": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard1.6": "ref/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Reflection.Emit.Lightweight.dll",
    },
    net_files = {
        "netstandard1.0": [
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.dll",
           "lib/netstandard1.0/System.Reflection.Emit.Lightweight.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        ],
        "netstandard1.4": [
           "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        ],
        "netstandard1.5": [
           "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        ],
        "netstandard1.6": [
           "lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Reflection.Emit.Lightweight.dll",
           "lib/netstandard2.0/System.Reflection.Emit.Lightweight.xml",
        ],
    },
)
nuget_package(
    name = "system.runtime.compilerservices.unsafe",
    package = "system.runtime.compilerservices.unsafe",
    version = "4.7.1",
    sha256 = "52fca80d5f0ed286371cf1b519b039e9855dbf04c611f8d8479816d4eec82b85",
    core_lib = {
        "netcoreapp2.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp2.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp3.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp3.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    core_ref = {
        "netcoreapp2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp3.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netcoreapp3.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    net_lib = {
        "net45": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net451": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net452": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net46": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net461": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net462": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net47": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net471": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net472": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net48": "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.0": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.1": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.2": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.3": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.4": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.5": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.6": "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard2.1": "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    net_ref = {
        "net45": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net451": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net452": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net46": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "net461": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net462": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net47": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net471": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net472": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "net48": "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.0": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.1": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.2": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.3": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.4": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.5": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard1.6": "ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        "netstandard2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
    },
    mono_lib = "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
    mono_ref = "ref/net461/System.Runtime.CompilerServices.Unsafe.dll",
    core_files = {
        "netcoreapp2.0": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netcoreapp2.1": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netcoreapp3.0": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netcoreapp3.1": [
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net451": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net452": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net46": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net461": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net462": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net47": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net471": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net472": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "net48": [
           "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.0": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard1.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
           "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.xml",
        ],
    },
    mono_files = [
        "lib/net461/System.Runtime.CompilerServices.Unsafe.dll",
        "lib/net461/System.Runtime.CompilerServices.Unsafe.xml",
    ],
)
nuget_package(
    name = "system.memory",
    package = "system.memory",
    version = "4.5.4",
    sha256 = "dec0847f33b8823e4260672d97d657411461c00ada3107ec7bbcb32a845eeb91",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/System.Memory.dll",
    },
    net_lib = {
        "net45": "lib/netstandard1.1/System.Memory.dll",
        "net451": "lib/netstandard1.1/System.Memory.dll",
        "net452": "lib/netstandard1.1/System.Memory.dll",
        "net46": "lib/netstandard1.1/System.Memory.dll",
        "net461": "lib/net461/System.Memory.dll",
        "net462": "lib/net461/System.Memory.dll",
        "net47": "lib/net461/System.Memory.dll",
        "net471": "lib/net461/System.Memory.dll",
        "net472": "lib/net461/System.Memory.dll",
        "net48": "lib/net461/System.Memory.dll",
        "netstandard1.1": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.2": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.3": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.4": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.5": "lib/netstandard1.1/System.Memory.dll",
        "netstandard1.6": "lib/netstandard1.1/System.Memory.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Memory.dll",
        "netstandard2.1": "lib/netstandard2.0/System.Memory.dll",
    },
    mono_lib = "lib/net461/System.Memory.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
        ],
    },
    net_deps = {
        "net45": [
           "@system.buffers//:net45_net",
           "@system.runtime.compilerservices.unsafe//:net45_net",
        ],
        "net451": [
           "@system.buffers//:net451_net",
           "@system.runtime.compilerservices.unsafe//:net451_net",
        ],
        "net452": [
           "@system.buffers//:net452_net",
           "@system.runtime.compilerservices.unsafe//:net452_net",
        ],
        "net46": [
           "@system.buffers//:net46_net",
           "@system.runtime.compilerservices.unsafe//:net46_net",
        ],
        "net461": [
           "@system.buffers//:net461_net",
           "@system.numerics.vectors//:net461_net",
           "@system.runtime.compilerservices.unsafe//:net461_net",
        ],
        "net462": [
           "@system.buffers//:net462_net",
           "@system.numerics.vectors//:net462_net",
           "@system.runtime.compilerservices.unsafe//:net462_net",
        ],
        "net47": [
           "@system.buffers//:net47_net",
           "@system.numerics.vectors//:net47_net",
           "@system.runtime.compilerservices.unsafe//:net47_net",
        ],
        "net471": [
           "@system.buffers//:net471_net",
           "@system.numerics.vectors//:net471_net",
           "@system.runtime.compilerservices.unsafe//:net471_net",
        ],
        "net472": [
           "@system.buffers//:net472_net",
           "@system.numerics.vectors//:net472_net",
           "@system.runtime.compilerservices.unsafe//:net472_net",
        ],
        "net48": [
           "@system.buffers//:net48_net",
           "@system.numerics.vectors//:net48_net",
           "@system.runtime.compilerservices.unsafe//:net48_net",
        ],
        "netstandard1.1": [
           "@system.buffers//:netstandard1.1_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.1_net",
        ],
        "netstandard1.2": [
           "@system.buffers//:netstandard1.2_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.2_net",
        ],
        "netstandard1.3": [
           "@system.buffers//:netstandard1.3_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.3_net",
        ],
        "netstandard1.4": [
           "@system.buffers//:netstandard1.4_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.4_net",
        ],
        "netstandard1.5": [
           "@system.buffers//:netstandard1.5_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@system.buffers//:netstandard1.6_net",
           "@system.runtime.compilerservices.unsafe//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@system.buffers//:netstandard2.0_net",
           "@system.numerics.vectors//:netstandard2.0_net",
           "@system.runtime.compilerservices.unsafe//:netstandard2.0_net",
        ],
        "netstandard2.1": [
           "@system.buffers//:netstandard2.1_net",
           "@system.numerics.vectors//:netstandard2.1_net",
           "@system.runtime.compilerservices.unsafe//:netstandard2.1_net",
        ],
    },
    mono_deps = [
        "@system.buffers//:mono",
        "@system.numerics.vectors//:mono",
        "@system.runtime.compilerservices.unsafe//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net451": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net452": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net46": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "net461": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "net462": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "net47": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "net471": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "net472": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "net48": [
           "lib/net461/System.Memory.dll",
           "lib/net461/System.Memory.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.1/System.Memory.dll",
           "lib/netstandard1.1/System.Memory.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/System.Memory.dll",
           "lib/netstandard2.0/System.Memory.xml",
        ],
    },
    mono_files = [
        "lib/net461/System.Memory.dll",
        "lib/net461/System.Memory.xml",
    ],
)
nuget_package(
    name = "system.threading.tasks.extensions",
    package = "system.threading.tasks.extensions",
    version = "4.5.4",
    sha256 = "a304a963cc0796c5179f9c6b7d8022bbce3b2fa7c029eb6196f631f7b462d678",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
    },
    net_lib = {
        "net45": "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
        "net451": "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
        "net452": "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
        "net46": "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
        "net461": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "net462": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "net47": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "net471": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "net472": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "net48": "lib/net461/System.Threading.Tasks.Extensions.dll",
        "netstandard1.0": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.1": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.2": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.3": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.4": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.5": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard1.6": "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
        "netstandard2.0": "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
        "netstandard2.1": "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
    },
    mono_lib = "lib/net461/System.Threading.Tasks.Extensions.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
        ],
    },
    net_deps = {
        "net45": [
           "@system.runtime.compilerservices.unsafe//:net45_net",
        ],
        "net451": [
           "@system.runtime.compilerservices.unsafe//:net451_net",
        ],
        "net452": [
           "@system.runtime.compilerservices.unsafe//:net452_net",
        ],
        "net46": [
           "@system.runtime.compilerservices.unsafe//:net46_net",
        ],
        "net461": [
           "@system.runtime.compilerservices.unsafe//:net461_net",
        ],
        "net462": [
           "@system.runtime.compilerservices.unsafe//:net462_net",
        ],
        "net47": [
           "@system.runtime.compilerservices.unsafe//:net47_net",
        ],
        "net471": [
           "@system.runtime.compilerservices.unsafe//:net471_net",
        ],
        "net472": [
           "@system.runtime.compilerservices.unsafe//:net472_net",
        ],
        "net48": [
           "@system.runtime.compilerservices.unsafe//:net48_net",
        ],
        "netstandard1.0": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.0_net",
        ],
        "netstandard1.1": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.1_net",
        ],
        "netstandard1.2": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.2_net",
        ],
        "netstandard1.3": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.3_net",
        ],
        "netstandard1.4": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.4_net",
        ],
        "netstandard1.5": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.5_net",
        ],
        "netstandard1.6": [
           "@system.runtime.compilerservices.unsafe//:netstandard1.6_net",
        ],
        "netstandard2.0": [
           "@system.runtime.compilerservices.unsafe//:netstandard2.0_net",
        ],
        "netstandard2.1": [
           "@system.runtime.compilerservices.unsafe//:netstandard2.1_net",
        ],
    },
    mono_deps = [
        "@system.runtime.compilerservices.unsafe//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.xml",
        ],
    },
    net_files = {
        "net45": [
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.xml",
        ],
        "net451": [
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.xml",
        ],
        "net452": [
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.xml",
        ],
        "net46": [
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.dll",
           "lib/portable-net45+win8+wp8+wpa81/System.Threading.Tasks.Extensions.xml",
        ],
        "net461": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "net462": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "net47": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "net471": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "net472": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "net48": [
           "lib/net461/System.Threading.Tasks.Extensions.dll",
           "lib/net461/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.0": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.1": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.2": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.3": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.4": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.5": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard1.6": [
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard1.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.dll",
           "lib/netstandard2.0/System.Threading.Tasks.Extensions.xml",
        ],
    },
    mono_files = [
        "lib/net461/System.Threading.Tasks.Extensions.dll",
        "lib/net461/System.Threading.Tasks.Extensions.xml",
    ],
)
nuget_package(
    name = "microsoft.bcl.asyncinterfaces",
    package = "microsoft.bcl.asyncinterfaces",
    version = "1.1.1",
    sha256 = "7c0717e2cc44d2f79633509906d5d1fd49e4cbeeac137df2ad5ee886b5862a28",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp2.1": "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp3.0": "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp3.1": "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
    },
    core_ref = {
        "netcoreapp2.0": "ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp2.1": "ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp3.0": "ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netcoreapp3.1": "ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
    },
    net_lib = {
        "net461": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net462": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net47": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net471": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net472": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net48": "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "netstandard2.0": "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netstandard2.1": "lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll",
    },
    net_ref = {
        "net461": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net462": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net47": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net471": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net472": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "net48": "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "netstandard2.0": "ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
        "netstandard2.1": "ref/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll",
    },
    mono_lib = "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
    mono_ref = "ref/net461/Microsoft.Bcl.AsyncInterfaces.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@system.threading.tasks.extensions//:netcoreapp2.0_core",
        ],
    },
    net_deps = {
        "net461": [
           "@system.threading.tasks.extensions//:net461_net",
        ],
        "net462": [
           "@system.threading.tasks.extensions//:net462_net",
        ],
        "net47": [
           "@system.threading.tasks.extensions//:net47_net",
        ],
        "net471": [
           "@system.threading.tasks.extensions//:net471_net",
        ],
        "net472": [
           "@system.threading.tasks.extensions//:net472_net",
        ],
        "net48": [
           "@system.threading.tasks.extensions//:net48_net",
        ],
        "netstandard2.0": [
           "@system.threading.tasks.extensions//:netstandard2.0_net",
        ],
        "netstandard2.1": [
           "@system.threading.tasks.extensions//:netstandard2.1_net",
        ],
    },
    mono_deps = [
        "@system.threading.tasks.extensions//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
    },
    net_files = {
        "net461": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "net462": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "net47": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "net471": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "net472": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "net48": [
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll",
           "lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.xml",
        ],
    },
    mono_files = [
        "lib/net461/Microsoft.Bcl.AsyncInterfaces.dll",
        "lib/net461/Microsoft.Bcl.AsyncInterfaces.xml",
    ],
)
nuget_package(
    name = "messagepack",
    package = "messagepack",
    version = "2.1.152",
    sha256 = "816b7238166dc83910df46294edfbd4b015773c3c6b9f1a145f59b64afe141cf",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/MessagePack.dll",
        "netcoreapp2.1": "lib/netcoreapp2.1/MessagePack.dll",
        "netcoreapp3.0": "lib/netcoreapp2.1/MessagePack.dll",
        "netcoreapp3.1": "lib/netcoreapp2.1/MessagePack.dll",
    },
    net_lib = {
        "net461": "lib/netstandard2.0/MessagePack.dll",
        "net462": "lib/netstandard2.0/MessagePack.dll",
        "net47": "lib/netstandard2.0/MessagePack.dll",
        "net471": "lib/netstandard2.0/MessagePack.dll",
        "net472": "lib/netstandard2.0/MessagePack.dll",
        "net48": "lib/netstandard2.0/MessagePack.dll",
        "netstandard2.0": "lib/netstandard2.0/MessagePack.dll",
        "netstandard2.1": "lib/netstandard2.0/MessagePack.dll",
    },
    mono_lib = "lib/netstandard2.0/MessagePack.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@messagepack.annotations//:netcoreapp2.0_core",
           "@microsoft.bcl.asyncinterfaces//:netcoreapp2.0_core",
           "@system.memory//:netcoreapp2.0_core",
           "@system.reflection.emit//:netcoreapp2.0_core",
           "@system.reflection.emit.lightweight//:netcoreapp2.0_core",
           "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
           "@system.threading.tasks.extensions//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@messagepack.annotations//:netcoreapp2.1_core",
           "@microsoft.bcl.asyncinterfaces//:netcoreapp2.1_core",
           "@system.memory//:netcoreapp2.1_core",
           "@system.reflection.emit//:netcoreapp2.1_core",
           "@system.reflection.emit.lightweight//:netcoreapp2.1_core",
           "@system.runtime.compilerservices.unsafe//:netcoreapp2.1_core",
           "@system.threading.tasks.extensions//:netcoreapp2.1_core",
        ],
        "netcoreapp3.0": [
           "@messagepack.annotations//:netcoreapp3.0_core",
           "@microsoft.bcl.asyncinterfaces//:netcoreapp3.0_core",
           "@system.memory//:netcoreapp3.0_core",
           "@system.reflection.emit//:netcoreapp3.0_core",
           "@system.reflection.emit.lightweight//:netcoreapp3.0_core",
           "@system.runtime.compilerservices.unsafe//:netcoreapp3.0_core",
           "@system.threading.tasks.extensions//:netcoreapp3.0_core",
        ],
        "netcoreapp3.1": [
           "@messagepack.annotations//:netcoreapp3.1_core",
           "@microsoft.bcl.asyncinterfaces//:netcoreapp3.1_core",
           "@system.memory//:netcoreapp3.1_core",
           "@system.reflection.emit//:netcoreapp3.1_core",
           "@system.reflection.emit.lightweight//:netcoreapp3.1_core",
           "@system.runtime.compilerservices.unsafe//:netcoreapp3.1_core",
           "@system.threading.tasks.extensions//:netcoreapp3.1_core",
        ],
    },
    net_deps = {
        "net461": [
           "@messagepack.annotations//:net461_net",
           "@microsoft.bcl.asyncinterfaces//:net461_net",
           "@system.memory//:net461_net",
           "@system.reflection.emit//:net461_net",
           "@system.reflection.emit.lightweight//:net461_net",
           "@system.runtime.compilerservices.unsafe//:net461_net",
           "@system.threading.tasks.extensions//:net461_net",
        ],
        "net462": [
           "@messagepack.annotations//:net462_net",
           "@microsoft.bcl.asyncinterfaces//:net462_net",
           "@system.memory//:net462_net",
           "@system.reflection.emit//:net462_net",
           "@system.reflection.emit.lightweight//:net462_net",
           "@system.runtime.compilerservices.unsafe//:net462_net",
           "@system.threading.tasks.extensions//:net462_net",
        ],
        "net47": [
           "@messagepack.annotations//:net47_net",
           "@microsoft.bcl.asyncinterfaces//:net47_net",
           "@system.memory//:net47_net",
           "@system.reflection.emit//:net47_net",
           "@system.reflection.emit.lightweight//:net47_net",
           "@system.runtime.compilerservices.unsafe//:net47_net",
           "@system.threading.tasks.extensions//:net47_net",
        ],
        "net471": [
           "@messagepack.annotations//:net471_net",
           "@microsoft.bcl.asyncinterfaces//:net471_net",
           "@system.memory//:net471_net",
           "@system.reflection.emit//:net471_net",
           "@system.reflection.emit.lightweight//:net471_net",
           "@system.runtime.compilerservices.unsafe//:net471_net",
           "@system.threading.tasks.extensions//:net471_net",
        ],
        "net472": [
           "@messagepack.annotations//:net472_net",
           "@microsoft.bcl.asyncinterfaces//:net472_net",
           "@system.memory//:net472_net",
           "@system.reflection.emit//:net472_net",
           "@system.reflection.emit.lightweight//:net472_net",
           "@system.runtime.compilerservices.unsafe//:net472_net",
           "@system.threading.tasks.extensions//:net472_net",
        ],
        "net48": [
           "@messagepack.annotations//:net48_net",
           "@microsoft.bcl.asyncinterfaces//:net48_net",
           "@system.memory//:net48_net",
           "@system.reflection.emit//:net48_net",
           "@system.reflection.emit.lightweight//:net48_net",
           "@system.runtime.compilerservices.unsafe//:net48_net",
           "@system.threading.tasks.extensions//:net48_net",
        ],
        "netstandard2.0": [
           "@messagepack.annotations//:netstandard2.0_net",
           "@microsoft.bcl.asyncinterfaces//:netstandard2.0_net",
           "@system.memory//:netstandard2.0_net",
           "@system.reflection.emit//:netstandard2.0_net",
           "@system.reflection.emit.lightweight//:netstandard2.0_net",
           "@system.runtime.compilerservices.unsafe//:netstandard2.0_net",
           "@system.threading.tasks.extensions//:netstandard2.0_net",
        ],
        "netstandard2.1": [
           "@messagepack.annotations//:netstandard2.1_net",
           "@microsoft.bcl.asyncinterfaces//:netstandard2.1_net",
           "@system.memory//:netstandard2.1_net",
           "@system.reflection.emit//:netstandard2.1_net",
           "@system.reflection.emit.lightweight//:netstandard2.1_net",
           "@system.runtime.compilerservices.unsafe//:netstandard2.1_net",
           "@system.threading.tasks.extensions//:netstandard2.1_net",
        ],
    },
    mono_deps = [
        "@messagepack.annotations//:mono",
        "@microsoft.bcl.asyncinterfaces//:mono",
        "@system.memory//:mono",
        "@system.reflection.emit//:mono",
        "@system.reflection.emit.lightweight//:mono",
        "@system.runtime.compilerservices.unsafe//:mono",
        "@system.threading.tasks.extensions//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "netcoreapp2.1": [
           "lib/netcoreapp2.1/MessagePack.dll",
           "lib/netcoreapp2.1/MessagePack.xml",
        ],
        "netcoreapp3.0": [
           "lib/netcoreapp2.1/MessagePack.dll",
           "lib/netcoreapp2.1/MessagePack.xml",
        ],
        "netcoreapp3.1": [
           "lib/netcoreapp2.1/MessagePack.dll",
           "lib/netcoreapp2.1/MessagePack.xml",
        ],
    },
    net_files = {
        "net461": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "net462": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "net47": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "net471": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "net472": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "net48": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/MessagePack.dll",
           "lib/netstandard2.0/MessagePack.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/MessagePack.dll",
        "lib/netstandard2.0/MessagePack.xml",
    ],
)
nuget_package(
    name = "messagepack.aspnetcoremvcformatter",
    package = "messagepack.aspnetcoremvcformatter",
    version = "2.1.152",
    sha256 = "2e914b89599c6f7ef6a4380fc0b9dfff5f24cd47776410af2b6e98d2bea6a707",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "netcoreapp2.1": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "netcoreapp3.0": "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "netcoreapp3.1": "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.dll",
    },
    net_lib = {
        "net461": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "net462": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "net47": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "net471": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "net472": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "net48": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "netstandard2.0": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "netstandard2.1": "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
    },
    mono_lib = "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
    core_deps = {
        "netcoreapp2.0": [
           "@messagepack//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@messagepack//:netcoreapp2.1_core",
        ],
        "netcoreapp3.0": [
           "@messagepack//:netcoreapp3.0_core",
        ],
        "netcoreapp3.1": [
           "@messagepack//:netcoreapp3.1_core",
        ],
    },
    net_deps = {
        "net461": [
           "@messagepack//:net461_net",
        ],
        "net462": [
           "@messagepack//:net462_net",
        ],
        "net47": [
           "@messagepack//:net47_net",
        ],
        "net471": [
           "@messagepack//:net471_net",
        ],
        "net472": [
           "@messagepack//:net472_net",
        ],
        "net48": [
           "@messagepack//:net48_net",
        ],
        "netstandard2.0": [
           "@messagepack//:netstandard2.0_net",
        ],
        "netstandard2.1": [
           "@messagepack//:netstandard2.1_net",
        ],
    },
    mono_deps = [
        "@messagepack//:mono",
        "@microsoft.aspnetcore.mvc.abstractions//:mono",
    ],
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "netcoreapp3.0": [
           "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "netcoreapp3.1": [
           "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netcoreapp3.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
    },
    net_files = {
        "net461": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "net462": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "net47": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "net471": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "net472": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "net48": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "netstandard2.0": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
        "netstandard2.1": [
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
           "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
        ],
    },
    mono_files = [
        "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.dll",
        "lib/netstandard2.0/MessagePack.AspNetCoreMvcFormatter.xml",
    ],
)
### End of generated by the tool
